# Generated by Django 2.1 on 2018-10-21 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentTime', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.CharField(max_length=42)),
                ('deleted', models.BooleanField(default=False)),
                ('Category', models.CharField(max_length=30)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, verbose_name='firstName')),
                ('lastName', models.CharField(max_length=30, verbose_name='lastName')),
                ('Age', models.IntegerField(default=0, verbose_name='age')),
                ('email', models.EmailField(max_length=30, verbose_name='email')),
                ('tel', models.CharField(max_length=11, verbose_name='tel')),
                ('whatsUp', models.CharField(max_length=42, verbose_name='whatsUp')),
                ('picture', models.ImageField(blank=True, default='grumblr-avators/default.png', upload_to='grumblr-avators')),
                ('follower', models.ManyToManyField(related_name='followed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.userProfile'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.userProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.post'),
        ),
    ]
