# Generated by Django 2.1 on 2018-10-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deleted',
        ),
    ]
